feat:　リモ達達成状況の更新APIの作成
Inazuma110/remotatsu_jumbo pull request #6
Opened 2021-08-20 05:46 UTC by Inazuma110

## やったこと
リモ達の達成状況を更新するAPIの作成。

## やらないこと
なし

## できるようになること（ユーザ目線）
リモ達の達成状況を更新できるようになる。
POSTで
```json
{
'remotatsu_state': [{"remotatsu_id": 1, "remotatsu_state": 1}, 
                                  {"remotatsu_id":2, "remotatsu_state": 0},
                               ...]
}
```
のように書く。
`remotatsu_state`が０は未達成、１は達成。
`"achieved": [1, 3, 5, ...]`のように達成した`remotatsu_id`の配列を渡すことも考えたが、「未達成だけど優先的にやる！」みたいな気持ちのステータスなどを増やしたい時に拡張しやすそうなのでこのような設計にしてみた。

## できなくなること（ユーザ目線）
なし

## 動作確認
postmanを用いて、`localhost/api/remotatsus_state`にPOST リクエストを送信し、DBの中をみる。

## その他
-　今日までの経験上、for文でInsertを何度も行うという処理があまり良くなさそう？
- RemotatsuTaskModel を作って、そこで`RemotatsuTaskModel::create(...)` のような実装の方が良い？

2021-08-20 06:31 UTC, Kai180621 commented on app/Http/Controllers/API/UserController.php
> +            return $tasks;
[GOOD] 処理自体はよくかけていると思います。Transactionも使えていてGOODです！
[IMAO] より良いコードにするために、処理の責務を分けると良いと思います。
例えば、L26の`if($state["remotatsus_state"] === 0) continue;`はvalidationという仕組みを使ってください。
https://readouble.com/laravel/8.x/ja/validation.html
また、L20 ~ L33まではService層に切り出すと良いと思います。
https://qiita.com/ntm718/items/14751e6d52b4bebde810

2021-08-20 07:08 UTC, yumemi-makiyama requested changes
全体的にLaravel的にこなれたコードになってきて Good

2021-08-20 07:08 UTC, yumemi-makiyama commented on app/Http/Controllers/API/UserController.php
> +            $remotatsu_tasks->where('user_id', $user_id)->delete();
[IMO]  いまさらいうな感はあるのだけど

```php
$remotatsu_tasks = DB::table('remotatsu_tasks');
$remotatsu_tasks->where('user_id', $user_id)->delete();
```
この部分は  `DB::table('remotatsu_tasks')` にあるテーブル名のtypoする可能性があるので、

```php
use App\Models\RemotatsuTask;

RemotatsuTask::where('user_id', $user_id)->delete();
```
とするとした方がよい。文字列でテーブル名を指定する代わりにモデルのクラス名を指定することで、PHPに対応した IDEなら警告を表示するので、間違いに気づくのが早くなる。

2021-08-23 02:50 UTC, Inazuma110 commented
@Kai180621 @yumemi-makiyama 
コメント頂いたところを修正しました！

2021-08-23 04:11 UTC, yumemi-makiyama approved these changes
@Inazuma110 ちゃんとサービスクラスに切り出され、モデルを使うコードは読みやすくなるので、非常によいです。

2021-08-23 04:41 UTC, Kai180621 approved these changes
LGTMです！

2021-08-23 04:42 UTC, merged